package com.jio.bahubali.enums;

public enum ShipmentStatus {
  ORDER_RECEIVED,
  ORDER_PROCESSED,
  ORDER_PICKED_UP,
  IN_TRANSIT,
  ARRIVED_AT_SORTING_CENTER,
  OUT_FOR_DELIVERY,
  DELIVERED,
  DELIVERY_ATTEMPT_FAILED,
  RETURNED_TO_SENDER,
  CANCELLED
}
